_BASE_: [
  './_base_/runtime.yml',
]

#for debug
eval_interval: 300
save_interval: 1000
weights: output/o2net
find_unused_parameters: True
save_dir: output
log_iter: 20

da_method: o2net_detr

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams

use_gpu: true
use_ema: False
### reader config
worker_num: 0

SemiTrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {prob: 0.8}
    - RandomExpand: {fill_value: [0., 0., 0.]}
    - RandomCrop: {prob: 0.8}
    - RandomFlip: {}
  weak_aug:
    - RandomFlip: {prob: 0.0}
  strong_aug:
    - StrongAugImage: {transforms: [
        RandomColorJitter: {prob: 0.8, brightness: 0.4, contrast: 0.4, saturation: 0.4, hue: 0.1},
        RandomErasingCrop: {},
        RandomGaussianBlur: {prob: 0.5, sigma: [0.1, 2.0]},
        RandomGrayscale: {prob: 0.2},
      ]}
  sup_batch_transforms:
    - BatchRandomResizeForSSOD: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  unsup_batch_transforms:
    - BatchRandomResizeForSSOD: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  sup_batch_size: 2
  unsup_batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: False
  use_shared_memory: false

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 2
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
    - Decode: {}
    - Resize: { target_size: [640, 640], keep_ratio: False }
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false


hidden_dim: 256
use_focal_loss: True
eval_size: [640, 640]


architecture: DA_DETR
DA_DETR:
  backbone: ResNet
  transformer: DA_DeformableTransformer
  detr_head: DA_DeformableDETRHead
  post_process: DETRPostProcess


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4


DeformableTransformer:
  num_queries: 300
  position_embed_type: sine
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.1
  activation: relu
  num_feature_levels: 4
  num_encoder_points: 4
  num_decoder_points: 4


DeformableDETRHead:
  num_mlp_layers: 3


DETRLoss:
  loss_coeff: {class: 2, bbox: 5, giou: 2}
  aux_loss: True


HungarianMatcher:
  matcher_coeff: {class: 2, bbox: 5, giou: 2}


metric: COCO
num_classes: 3

# partial labeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
TrainDataset:
  !SemiCOCODataSet
    image_dir: train
    anno_path: train/train_0624.json
    dataset_dir: /root/paddlejob/workspace/env_run/datasets/rails_danger_tl
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
# partial unlabeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
UnsupTrainDataset:
  !SemiCOCODataSet
    image_dir: train_t
    anno_path: train_t/train_target.json
    dataset_dir: /root/paddlejob/workspace/env_run/datasets/rails_danger_tl
    data_fields: ['image']
    supervised: False

EvalDataset:
  !COCODataSet
    image_dir: eval
    anno_path: eval/eval_0624_bg.json
    dataset_dir: /root/paddlejob/workspace/env_run/datasets/rails_danger_tl
    allow_empty: true

TestDataset:
  !ImageFolder
    anno_path: "" # also support txt (like VOC's label_list.txt)
    dataset_dir: "" # if set, anno_path will be 'dataset_dir/anno_path'

epoch: 60

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 1.0
    milestones: [500]
    use_warmup: false
  - !LinearWarmup
    start_factor: 0.001
    steps: 200

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001