_BASE_: [
  '../../datasets/coco_detection.yml',
  '../../runtime.yml',
  '../_base_/optimizer_80e.yml',
  '../_base_/ppyoloe_plus_crn.yml',
  '../_base_/ppyoloe_plus_reader.yml',
]

save_dir: output/ppyoloe_x
log_iter: 100
snapshot_epoch: 5
weights: output/ppyoloe_plus_crn_x_60e_objects365/model_final
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_x_obj365_pretrained.pdparams

CSPResNet:
  use_alpha: False

PPYOLOEHead:
  static_assigner_epoch: 20

depth_mult: 1.33
width_mult: 1.25
