_BASE_: [
  '../../datasets/coco_detection.yml',
  '../../runtime.yml',
  '../_base_/optimizer_80e.yml',
  '../_base_/ppyoloe_plus_crn.yml',
  '../_base_/ppyoloe_plus_reader.yml',
]

save_dir: output/luce
log_iter: 100
snapshot_epoch: 1
weights: output/ppyoloe_plus_crn_m_60e_objects365/model_final
# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_m_pretrained.pdparams
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_m_obj365_pretrained.pdparams

CSPResNet:
  use_alpha: False

PPYOLOEHead:
  static_assigner_epoch: 20

depth_mult: 0.67
width_mult: 0.75
