_BASE_: [
  # '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: output/rtdetr_r50vd_6x_coco/model_final
find_unused_parameters: True
log_iter: 50



metric: COCO
num_classes: 8
classwise: true
save_dir: output/rtdetr_r50vd_6x_coco_cityscapes2foggycityscapes


# FoggyCityScapes
# TrainDataset:
#   name: COCODataSet
#   image_dir: leftImg8bit_foggy/train
#   anno_path: label/foggy_cityscapes_train.json
#   dataset_dir: data/cityscapes
#   data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

# CityScapes
TrainDataset:
  name: COCODataSet
  image_dir: leftImg8bit/train
  anno_path: label/cityscapes_train.json
  dataset_dir: data/cityscapes
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

# TrainDataset:
#   name: COCODataSet
#   image_dir: VOC2012/JPEGImages
#   anno_path: sim10k/sim10k_caronly_new.json
#   dataset_dir: data
#   data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']


# EvalDataset:
#   name: COCODataSet
#   image_dir: leftImg8bit/val
#   anno_path:  label/cityscapes_caronly_val.json
#   dataset_dir: data/cityscapes
#   allow_empty: false


# BDD100K
# EvalDataset:
#   name: COCODataSet
#   image_dir: images/100k/val
#   anno_path:  annotations/bdd_daytime_val.json
#   dataset_dir: data/bdd100k
#   allow_empty: false

# FoggyCityscapes
EvalDataset:
  name: COCODataSet
  image_dir: leftImg8bit_foggy/val
  anno_path:  label/foggy_cityscapes_val.json
  dataset_dir: data/cityscapes
  allow_empty: false

TestDataset:
  name: ImageFolder
  anno_path:  # also support txt (like VOC's label_list.txt)
  dataset_dir:  # if set, anno_path will be 'dataset_dir/anno_path'